name: Mermaid Maker
description: Convert mermaid files into image formats.
inputs:
  input_dir:
    description: |
      The input directory for mermaid files. Defaults to "all",
      i.e. all changed files with input_file_extension across the whole repo.
    required: false
    default: all
    type: string
  input_file_extension:
    description: The extension of the mermaid files.
    required: false
    default: mmd
    type: string
  output_dir:
    description: |
      The output directory for generated mermaid files. Defaults to "same",
      i.e. converted files will be placed in the same directory as their source files.
    required: false
    default: same
    type: string
  output_file_extension:
    description: |
      The output format of the generated mermaid files. Only "svg", "png"and "pdf" are accepted. 
    required: false
    default: svg
    type: string
  commit:
    description: |
      Whether generated mermaid files should be committed to the repo.
    required: false
    default: false
    type: boolean
  commit_message:
    description: |
      The commit message used for commiting mermaid files into the repository. 
      Defaults to: "feat: Convert `input_file_extension` file(s) to `output_file_extension`".
    required: false
    default: ''
    type: string
  pkg_manager:
    description: |
      The node package manager to use. Make sure it's setup before using this action.
      Currently, only the following pkg_managers are accepted:
        - "npm"   
        - "pnpm"  
        - "yarn" 
        - "bun"   
    required: false
    default: npm
    type: string
branding:
  icon: arrow-down-circle
  color: purple
runs:
  using: composite
  steps:
    - name: Get all the input mermaid files
      run: |
        import json
        from glob import glob
        from os import environ


        def get_input_files(input_dir, input_file_extension, output_file):

            if input_dir == "all":
                input_files_glob_pattern = f"**/*.{input_file_extension}"
            else:
                input_files_glob_pattern = f"{input_dir}/**/*.{input_file_extension}"

            input_files = glob(input_files_glob_pattern, recursive=True)

            with open(output_file, "a") as file:
                print("input_files=" + json.dumps(input_files), file=file)


        if __name__ == "__main__":
            get_input_files(
                environ["INPUT_DIR"], environ["INPUT_FILE_EXTENSION"], environ["GITHUB_OUTPUT"]
            )
      id: get_input_files
      shell: python
      env:
        INPUT_DIR: ${{inputs.input_dir}}
        INPUT_FILE_EXTENSION: ${{inputs.input_file_extension}}
    - name: Get all the existing, generated mermaid files (if they exist)
      run: |
        import json
        from os import environ
        from os.path import basename
        from pathlib import Path


        def get_output_files(input_files, output_dir, output_file_extension, output_file):
            output_files = []

            if output_dir == "same":
                for file in input_files:
                    output_files.append(
                        Path(file).with_suffix(f".{output_file_extension}").as_posix()
                    )
            else:
                for file in input_files:
                    output_files.append(
                        (Path(output_dir) / basename(file))
                        .with_suffix(f".{output_file_extension}")
                        .as_posix()
                    )
                if len(output_files) != len(set(output_files)):
                    raise FileExistsError(
                        "If you are specifying an output directory, please ensure your input mermaid files have unique names."
                    )

            with open(output_file, "a") as file:
                print(f"output_files={json.dumps(output_files)}", file=file)


        if __name__ == "__main__":
            get_output_files(
                json.loads(environ["INPUT_FILES"]),
                environ["OUTPUT_DIR"],
                environ["OUTPUT_FILE_EXTENSION"],
                environ["GITHUB_OUTPUT"],
            )
      id: get_output_files
      env:
        INPUT_FILES: ${{steps.get_input_files.outputs.input_files}}
        OUTPUT_DIR: ${{inputs.output_dir}}
        OUTPUT_FILE_EXTENSION: ${{inputs.output_file_extension}}
      shell: python
    - name: Get all the input/ouput files that must be (re)generated
      run: |
        import json
        from os import environ
        from os.path import getmtime
        from pathlib import Path


        def get_files_to_regen(input_files, output_files, output_file):
            input_files_to_regen = []
            output_files_to_regen = []

            for i in range(len(input_files)):
                output_file_exists = Path(output_files[i]).exists()

                # we want to skip generating mermaid diagrams when:
                # 1. output file exists, AND
                # 2. output file is newer or as new as the input file
                # this is the negation of that
                if not output_file_exists or (
                    getmtime(input_files[i]) > getmtime(output_files[i])
                ):
                    input_files_to_regen.append(input_files[i])
                    output_files_to_regen.append(output_files[i])

            with open(output_file, "a") as file:
                print("input_files_to_regen=" + json.dumps(input_files_to_regen), file=file)
                print("output_files_to_regen=" + json.dumps(output_files_to_regen), file=file)


        if __name__ == "__main__":
            get_files_to_regen(
                json.loads(environ["INPUT_FILES"]),
                json.loads(environ["OUTPUT_FILES"]),
                environ["GITHUB_OUTPUT"],
            )
      shell: python
      id: get_files_to_regen
      env:
        INPUT_FILES: ${{steps.get_input_files.outputs.input_files}}
        OUTPUT_FILES: ${{steps.get_output_files.outputs.output_files}}
    - if: ${{steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      name: Set pkg_manager run commmand
      env:
        PKG_MANAGER: ${{inputs.pkg_manager}}
      run: |
        from os import environ


        def set_pkg_manager_run(pkg_manager, output_file):
            pkg_manager_run_cmd = ""
            if pkg_manager == "npm":
                pkg_manager_run_cmd = "npx"
            elif pkg_manager == "pnpm":
                pkg_manager_run_cmd = "pnpm"
            elif pkg_manager == "yarn":
                pkg_manager_run_cmd = "yarn dlx"
            elif pkg_manager == "bun":
                pkg_manager_run_cmd = "bunx"
            else:
                raise ValueError("Inputted pkg_manager is not recognized")

            with open(output_file, "a") as file:
                print("pkg_manager_run_cmd=" + pkg_manager_run_cmd, file=file)


        if __name__ == "__main__":
            set_pkg_manager_run(environ["PKG_MANAGER"], environ["GITHUB_OUTPUT"])
      id: set_pkg_manager_run
      shell: python
    - if: ${{steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      name: Package manager setup
      run: |
        from os import environ
        from subprocess import run


        def pkg_manager_setup(pkg_manager):
            if pkg_manager == "npm":
                print("Nothing to setup")
            elif pkg_manager == "pnpm":
                run(
                    ["pnpm", "config", "set", "--location=project", "strictDepBuilds", "false"],
                    check=True,
                )
            elif pkg_manager == "yarn":  # noqa: SIM114
                print("Nothing to setup")
            elif pkg_manager == "bun":
                print("Nothing to setup")
            else:
                raise ValueError("Inputted pkg_manager is not recognized")


        if __name__ == "__main__":
            pkg_manager_setup(environ["PKG_MANAGER"])
      shell: python
      id: pkg_manager_setup
      env:
        PKG_MANAGER: ${{inputs.pkg_manager}}
    - if: ${{steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      name: install mermaid
      run: |
        ### install mermaid
        PUPPETEER_SKIP_DOWNLOAD='true' ${{inputs.pkg_manager}} install @mermaid-js/mermaid-cli@11.16.0
      shell: bash
    - name: get puppeteer version
      id: puppeteer_version
      run: echo "version=$(${{inputs.pkg_manager}} puppeteer --version | tail -n 1)" >> "$GITHUB_OUTPUT"
      shell: bash
    - if: ${{steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      name: Restore mermaid browser (if it exists)
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
      with:
        key: mermaid-maker-chrome-browser-puppeteer@${{steps.puppeteer_version.outputs.version}}
        path: mermaid-maker-chrome-browser
      id: restore-browser
    - if: ${{steps.restore-browser.outputs.cache-hit != 'true' && steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      name: install browser if doesnt exist
      run: |
        ### install browser if doesnt exist
        PUPPETEER_CACHE_DIR='./mermaid-maker-chrome-browser' ${{steps.set_pkg_manager_run.outputs.pkg_manager_run_cmd}} puppeteer browsers install
      shell: bash
    - if: ${{steps.restore-browser.outputs.cache-hit != 'true' && steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      name: cache mermaid browser
      uses: actions/cache/save@v6.1.0
      with:
        key: ${{steps.restore-browser.outputs.cache-primary-key}}
        path: mermaid-maker-chrome-browser
    - if: ${{steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      id: mermaid_gen
      name: Generate mermaid diagrams
      env:
        INPUT_FILES_TO_REGEN: ${{steps.get_files_to_regen.outputs.input_files_to_regen}}
        OUTPUT_FILES_TO_REGEN: ${{steps.get_files_to_regen.outputs.output_files_to_regen}}
        RUN_CMD: ${{steps.set_pkg_manager_run.outputs.pkg_manager_run_cmd}}
      run: |
        import json
        from os import environ
        from subprocess import run


        def mermaid_gen(input_files_to_regen, output_files_to_regen, run_cmd):

            mermaid_env = [
                "env",
                "PUPPETEER_CACHE_DIR=mermaid-maker-chrome-browser",
                "aa-exec",
                "--profile=chrome",
            ]

            # generate mermaid diagram for each changed file
            for i in range(len(input_files_to_regen)):
                mermaid_cmd = [
                    "mmdc",
                    "-i",
                    input_files_to_regen[i],
                    "-o",
                    output_files_to_regen[i],
                    "-b",
                    "transparent",
                ]

                run(mermaid_env + [run_cmd] + mermaid_cmd, check=True)


        if __name__ == "__main__":
            mermaid_gen(
                json.loads(environ["INPUT_FILES_TO_REGEN"]),
                json.loads(environ["OUTPUT_FILES_TO_REGEN"]),
                environ["RUN_CMD"],
            )
      shell: python
    - if: ${{inputs.commit_message == '' && steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      name: Set commit message
      id: COMMIT_MSG
      run: |
        ### Set commit message
        echo "SET_COMMIT_MSG='feat: Convert .${{inputs.input_file_extension}} file(s) to ${{inputs.output_file_extension}}'" >> "$GITHUB_OUTPUT"
      shell: bash
    - if: ${{inputs.commit == true && steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321
      with:
        message: ${{steps.COMMIT_MSG.outputs.SET_COMMIT_MSG}}
        add: ${{steps.get_files_to_regen.outputs.output_files_to_regen}}
    - if: ${{steps.get_files_to_regen.outputs.input_files_to_regen != '[]'}}
      name: Package manager teardown
      env:
        PKG_MANAGER: ${{inputs.pkg_manager}}
      run: |
        from os import environ
        from subprocess import run


        def pkg_manager_teardown(pkg_manager):
            if pkg_manager == "npm":
                print("Nothing to teardown")
            elif pkg_manager == "pnpm":
                run(
                    ["pnpm", "config", "set", "--location=project", "strictDepBuilds", "true"],
                    check=True,
                )
            elif pkg_manager == "yarn":  # noqa: SIM114
                print("Nothing to teardown")
            elif pkg_manager == "bun":
                print("Nothing to teardown")
            else:
                raise ValueError("Inputted pkg_manager is not recognized")


        if __name__ == "__main__":
            pkg_manager_teardown(environ["PKG_MANAGER"])
      shell: python
      id: pkg_manager_teardown
