set default-list

# format then lint
all: format lint

# lint with ruff
lint:
    uv run ruff check .

# format with black
format:
    uv run black .

# bundle in an interactive way
ibundle:
    python bundler.py

# run unit tests
test:
    uv run pytest
