name: CI (formatting, linting, unit-tests)
on: 
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
    workflow_dispatch:

jobs:
    py-ci:
        runs-on: ubuntu-latest
        steps:
            - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"
              with:
                sparse-checkout: |
                  py_files
            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
              with:
                working-directory: "py_files"
            - name: format with black
              run: |
                cd py_files
                uv run black .
            - name: lint with ruff
              run: |
                cd py_files
                uv run ruff check
            - name: Run Unit tests
              run: |
                cd py_files
                uv run --locked pytest
    bundle-python-to-action:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"
        - name: setup pnpm
          uses: "pnpm/action-setup@v6.0.10"
          with:
            cache: true
            cache_dependency_path: |
              py_files_to_action_bundler/pnpm-lock.yaml
            version: 11
            run_install: |
                - cwd: py_files_to_action_bundler
        - name: run bundler
          run: |
            cd py_files_to_action_bundler
            pnpm bundle_to_action
        - name: check for diff and exit with error with a diff
          run: | 
            git diff --exit-code action.yml 